inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/ClassLength:
  Max: 300

Style/CollectionMethods:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
