sudo: false
language: ruby
cache: bundler

branches:
  except:
    - rails-2_3
    - rails-3_2

rvm:
  - "2.1.8"
  - "2.2.4"
  - "2.3.0"

gemfile: hawk/Gemfile
script: sh -c 'cd hawk && bin/rake brakeman:run test'
notifications:
  irc: "chat.freenode.net#clusterlabs-dev"
